[package]
name = "WinLogon"
version = "0.1.0"
edition = "2021"

[dependencies]
winreg = "0.10.1"
winapi = { version = "0.3.9", features = ["winnt", "processthreadsapi", "securitybaseapi", "handleapi", "winbase", "errhandlingapi"] }
widestring = "0.4.3"
